<a href="https://colab.research.google.com/github/bilalotw/ictinternship/blob/main/day_2_numpy_and_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
list1=[1,2,3,4]
list2=[5,6,7,8]
sum_1=[]
for num1,num2 in zip(list1,list2):
    sum_1.append(num1+num2)
sum_1

[6, 8, 10, 12]

In [ ]:
import numpy as np
import pandas as pd


In [ ]:
arr1= np.array(list1)
arr2= np.array(list2)
arr1

array([1, 2, 3, 4])

arr2

In [ ]:
np.ndim(arr1)

1

In [ ]:
list3=[[1,2,3],[1,2,3],[1,2,3]]
arr4=np.array(list3)
np.ndim(arr4)

2

In [ ]:
arr4.shape

(3, 3)

In [ ]:
np.ndim(arr4)

2

In [ ]:
arr5=np.arange(7)
arr5

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
arr6=arr5.reshape(2,3)
arr6

In [ ]:
arr5.mean()

3.0

In [ ]:
np.sqrt(arr5)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.random.rand(3,4)

array([[0.884029  , 0.27203987, 0.25656828, 0.27150825],
       [0.36569465, 0.02465937, 0.53617292, 0.30976284],
       [0.32494426, 0.55510151, 0.14833665, 0.34475251]])

In [ ]:
data=pd.read_csv('/content/datset/auto-mpg.csv')
data

mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0   
1    15.0          8         350.0        165    3693          11.5   
2    18.0          8         318.0        150    3436          11.0   
3    16.0          8         304.0        150    3433          12.0   
4    17.0          8         302.0        140    3449          10.5   
..    ...        ...           ...        ...     ...           ...   
393  27.0          4         140.0         86    2790          15.6   
394  44.0          4          97.0         52    2130          24.6   
395  32.0          4         135.0         84    2295          11.6   
396  28.0          4         120.0         79    2625          18.6   
397  31.0          4         119.0         82    2720          19.4   

     model year  origin                   car name  
0            70       1  chevrolet chevelle malibu  
1            70       1          buick skylark 320  
2            70       1         plymouth satellite  
3            70       1              amc rebel sst  
4            70       1                ford torino  
..          ...     ...                        ...  
393          82       1            ford mustang gl  
394          82       2                  vw pickup  
395          82       1              dodge rampage  
396          82       1                ford ranger  
397          82       1                 chevy s-10  

[398 rows x 9 columns]